### PR TITLE
Use Conda to install additional packages

### PR DESCRIPTION
**Pull request by jakirkham**
Fix install issues resulting in CI failures where PyPy is getting pulled in unexpectedly

### CODE REVIEW

**Comment by msarahan** [comment]
I think the purpose here was to try to work around the confusion with some of the images having Pypy instead of cpython, right? Was there another reason here?

**Comment by jakirkham** [comment]
Yes that was the main motivator

There may be secondary considerations between these 2 options, but fixing CI is the goal

**Comment by msarahan** [comment]
In that case, I think https://github.com/rapidsai/miniforge-cuda/pull/52 is a better fix that serves the same purpose. OK with closing this?

**Comment by jakirkham** [comment]
Sure we can always revisit if needed

**Pull request closed without merging**
