### PR TITLE
Add Python 3.9 back temporarily for a `24.08` hotfix

### PR DESCRIPTION
**Pull request by raydouglass**
We're planning one final hotfix for `24.08` which supports Python 3.9, so add it back here out an abundance of caution. Without this, the Python 3.9 builds will use outdated images.

This can undone in ~2 weeks.

### CODE REVIEW

**Comment by jameslamb** [comment]
Looks like you're running into the same `ci-conda` build issues I've been seeing on other PRs here this morning.

I'm tracking that in #185 and I'm using #183 to investigate.

**Comment by jameslamb** [comment]
@raydouglass I put up a hack to temporarily fix CI in #186 . It could be merged to unblock CI here for the purposes of rolling out this 24.08 hotfix if you need something quick.

**Comment by raydouglass** [comment]
> @raydouglass I put up a hack to temporarily fix CI in #186 . It could be merged to unblock CI here for the purposes of rolling out this 24.08 hotfix if you need something quick.

Thanks @jameslamb! This is not urgent and can wait a couple days for a solution.

**Comment by jameslamb** [comment]
Thanks @raydouglass ! We got #186 to a point where it now contains a long-term solution and not a hack 😁 

Once I merge that to `main`, I'll update this PR and merge it for you if you'd like.

**Review by msarahan — APPROVED** [review]

**Comment by jameslamb** [comment]
Thanks for the review @msarahan !

@raydouglass I opened #187 to track the work of reverting this in a few weeks.

**Pull request merged**
